[workspace]
authors = ["Carol Willing <carolcode@willingconsulting.com>"]
channels = ["conda-forge"]
name = "team-compass"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
dev = "zensical serve"
build = "zensical build"

[dependencies]
zensical = ">=0.0.53,<0.0.54"
