"""Write the dev server's config: zensical.toml with site_url pointed at `addr`.

`navigation.instant` fetches `sitemap.xml` from the absolute `site_url` to work
out which links are internal. Against the production URL that request is
cross-origin, the browser refuses it, and instant navigation quietly degrades to
full page loads while the console fills with CORS errors.

Zensical has no environment-specific configuration for `.toml` projects, so the
dev server builds from a generated copy instead. It watches the copy, not the
original, so a change to `zensical.toml` needs a restart to take effect.

Usage: python scripts/dev_config.py localhost:8001
"""

import re
import sys
from pathlib import Path

SOURCE = Path("zensical.toml")
TARGET = Path(".zensical.serve.toml")


def main(addr: str) -> None:
    config, count = re.subn(
        r"(?m)^site_url\s*=.*$",
        f'site_url = "http://{addr}/"',
        SOURCE.read_text(),
    )
    if count != 1:
        sys.exit(f"expected one site_url in {SOURCE}, found {count}")
    TARGET.write_text(f"# Generated by scripts/dev_config.py. Edit {SOURCE} instead.\n{config}")


if __name__ == "__main__":
    main(sys.argv[1])
